name: Auto-update JSON and Mobileconfig files
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update JSON and Mobileconfig files
      run: |
        # 在此处编写您的脚本以自动更新JSON和Mobileconfig文件
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update JSON and Mobileconfig files
        commit_options: '--no-verify'
