name: 定时任务

on:
  push:
  schedule:
    - cron: '*/30 * * * *'
    - cron: '0 0 * * *'

jobs:
  run_code:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: 安装依赖
        run: pip install requests

      - name: 运行代码
        run: |
          python ipsw.py

      - name: 创建 Deploy 文件夹
        run: mkdir -p deploy

      - name: 将生成的文件移动到 Deploy 文件夹
        run: |
          mv *.json deploy/

      - name: 将生成的文件复制回工作目录
        run: cp -R deploy/* $GITHUB_WORKSPACE/

      - name: 配置 Git
        run: |
          git config --global user.name 'y0123456789'
          git config --global user.email '52168408+y0123456789@users.noreply.github.com'

      - name: 提交和推送变更到 gh-pages 分支
        run: |
          git checkout -B gh-pages
          git rm -rf .
          git checkout main -- CNAME
          if [ ! -f "./CNAME" ]; then
            cp CNAME .
          fi
          cp -R deploy/* .
          git add .
          git commit -m "Update files"
          git push -f origin gh-pages
