name: Build HTML Docs

on:
  push:
  schedule:
    - cron: '*/30 * * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Build Files
        uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deps
        run: |
          python -m pip install --upgrade pip
          echo 'requests' >> requirements.txt
          echo 'datetime' >> requirements.txt
          echo 'urllib3' >> requirements.txt
          echo 'jinja2' >> requirements.txt
          pip install -r requirements.txt
          pip3 install hammock python-dateutil packaging urllib3
      
      - name: Run yanchi.py
        run: |
          python3 -u yanchi.py
          
      - name: Create Deploy Folder
        run: mkdir -p deploy
      
      - name: Move Files to Deploy Folder
        run: |
          mv yanchi.json deploy/yanchi.json
          mv *.mobileconfig deploy/
      
      - name: Copy Files to Workspace
        run: cp -R deploy/* $GITHUB_WORKSPACE/
      
      - name: Configure Git
        run: |
          git config --global user.name 'y0123456789'
          git config --global user.email '52168408+y0123456789@users.noreply.github.com'
      
      - name: Commit and Push Changes
        run: |
          git checkout -B gh-pages
          git rm -rf .
          git checkout main -- CNAME
          if [ ! -f "./CNAME" ]; then
          cp CNAME .
          fi
          cp -R deploy/* .
          git add .
          git commit -m "Update files"
          git push -f origin gh-pages
      
      - name: Upload Files to Server
        uses: SamKirkland/FTP-Deploy-Action@4.1.1
        with:
          server: 124.221.182.210
          username: 15079770750
          password: rrXztM27bAXncJNy
          local-dir: ./deploy
          remote-dir: /www/wwwroot/github
