name: Run yanchi.py

on:
  schedule:
    - cron: '*/40 * * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
        run: |
        pip install requests urllib3 jinja2
        python3 -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install datetime
        python3 -u yanchi.py

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
          branch: gh-pages
          folder: deploy
