name: Build HTML Docs

on:
  push:
  schedule:
    - cron: '*/40 * * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Build Files
        uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deps
        run: |
          python -m pip install --upgrade pip
          echo 'requests' >> requirements.txt
          echo 'datetime' >> requirements.txt
          echo 'urllib3' >> requirements.txt
          echo 'jinja2' >> requirements.txt
          pip install -r requirements.txt
          pip3 install hammock python-dateutil packaging urllib3
      
      - name: Run yanchi.py
        run: |
          python3 -u yanchi.py

      - name: Upload files to workflow
        uses: actions/upload-artifact@v2
        with:
          name: MobileConfig and yanchi.json
          path: |
            ./mobileconfig
            ./yanchi.json

      - name: Download files from workflow
        uses: actions/download-artifact@v2
        with:
          name: MobileConfig and yanchi.json

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: .
          token: ${{ secrets.GITHUB_TOKEN }}
          if-no-branch: create

      - name: Overwrite mobileconfig and yanchi.json
        run: |
          cp -f ${{ github.workspace }}/MobileConfig\ and\ yanchi.json/mobileconfig/*.mobileconfig ./mobileconfig/
          cp -f ${{ github.workspace }}/MobileConfig\ and\ yanchi.json/yanchi.json ./
